### ISSUE TITLE
An idea for your project.

### ISSUE THREAD

**Issue by rainautumn** [ifedyukin/React-ToDoList#1]
Pleace, add to your repo python(or another) script for LAN worcks. 
..
All the best.

**Comment by ifedyukin** [comment]
@rainautumn you can run localhost-application via **nodeJS** and **npm**, but items will be stored only in your browser:
```bash
git clone https://github.com/ifedyukin/React-ToDoList
cd React-ToDoList    
npm install
npm start
```

Also share the "docs" folder on the local server, for examle:
```bash
npm install http-server -g
git clone https://github.com/ifedyukin/React-ToDoList
cd React-ToDoList/docs
npm http-server
```

I can make a version that works with Backend (JSON).

> Очень плохой английский у меня, но что поделать...

**Comment by rainautumn** [comment]
You can create free browser app. for example (py27):

```
#!/usr/bin/python

import os
import gtk
import webkit

  win = gtk.Window(gtk.WINDOW_POPUP)
  bro = webkit.WebView()
  bro.open("http://localhost")
  win.add(bro)
  win.show()
  bro.show()
  gtk.main()
```

**Comment by ifedyukin** [comment]
@rainautumn this is a browser application. For start:
```bash
git clone https://github.com/ifedyukin/React-ToDoList
cd React-ToDoList/docs
npm http-server
```
Magic :sparkles:

**Comment by rainautumn** [comment]
Please add to repo script to freebrowser works. 
>this is a browser application

**Comment by ifedyukin** [comment]
I can't create GTK application, because I'm use Windows.
I am waiting for your pull request.

**Comment by rainautumn** [comment]
Чё закрыл то?

**Comment by ifedyukin** [comment]
@rainautumn ну, если накидаешь PR, то открою и прикреплю. 
Хотя подожди, скоро другая версия будет, в неё будешь уже реквесты кидать.

**Comment by rainautumn** [comment]
Дурашка. я гитхаб свой белее делаю. 
Я всем(почти всем)  знакомым сказал что сдох. и зелёный квадратос на гитхабе это ппц как апровергнет. 
..
Хотя я могу PR если фейк сделаю.

**Comment by ifedyukin** [comment]
@rainautumn обожди, и сделаешь реквест на новую версию. Я тебе на почту линк скину, как залью.

**Comment by rainautumn** [comment]
Тока попозже. через месяцок

**Comment by ifedyukin** [comment]
@rainautumn оно примерно так и получится.

**Comment by DmitryHetman** [comment]
@rainautumn А зачем?
