### ISSUE TITLE
Bug with "space" item value

### ISSUE THREAD

**Issue by discorpsee** [ifedyukin/React-ToDoList#2]
When I enter "space" in input - bug. 
<img width="631" alt="2017-02-07 15 59 35" src="https://cloud.githubusercontent.com/assets/23001035/22692111/848d5df8-ed4e-11e6-849f-446f56cb2193.png">

**Comment by andnikolaev** [comment]
Yeah, yeah. This shit happened with me too. I was very sad on this moment.:rage:
